### ISSUE TITLE
 Can‘t configure anymore via serial interface 

### ISSUE THREAD

**Issue by susisstrolch** [proddy/EMS-ESP#141]
With  current dev it‘s not longer possible to configure before the WIFI parameters are set in AP-mode. 
Older version (at least b2) allows to configure anything via serial, omitting the steps AP config and Telnet to the flashed device.

**Comment by proddy** [comment]
that's correc, it's by design. Serial is disabled on an initial install as most users will be noobs that purchase a circuit board with the firmware pre-loaded. I'm open to suggestions though...what do you recommend?

**Comment by susisstrolch** [comment]
I‘d suggest to keep the serial enabled. Imho with webinterface it‘s even for noobs easy  to switch to EMS-mode. Showing a „connect to EMS“ button would hide the ‚set serial on‘ but keep freedom to the experianced ones.

**Comment by bbqkees** [comment]
I would keep it off by default.
I think of two kinds of people who would use the firmware.
One are the experienced guys like you who know how to build it, and those who either buy a preprogrammed one or can barely load the bin file on the Wemos themselves.

It's easier for an experienced user to change a build flag in the ini file to set serial on and then build and load the firmware than it is for 'noobs' to have yet another setting to make.
Major thing is that setting serial on by default disconnects you from the EMS bus initially which prevents you from using the firmware for its intended purpose: communicating with the EMS bus.
We know its like that because the ESP8266 only has one UART. People new to all this likely don't.

When plugging in the device to the boiler for the very first time its already quite comforting to have the blinking LED go solid so at least you know it had found the EMS bus before making any further settings.

I also found that when in AP mode (at least until 1.8.1b2), changing the serial to off is not persistent.
So on next boot its still on.

**Comment by susisstrolch** [comment]
> It's easier for an experienced user to change a build flag in the in

Sounds fair...

Which flag - NO_SERIAL (as written in CHANGELOG.md) or DEFAULT_NO_SERIAL 
(as implemented in MyESP.cpp)?

**Comment by bbqkees** [comment]
As I understood it now its -DNO_SERIAL in the ini file.

**Comment by proddy** [comment]
sorry guys, it's DEFAULT_NO_SERIAL. I keep changing my mind ;)

**Comment by proddy** [comment]
actually changed again to `-DFORCE_SERIAL`. Think I got it right this time in 1.8.1b23
