### ISSUE TITLE
Security: raw wifi password is sent via websocket

### ISSUE THREAD

**Issue by petercipov** [proddy/EMS-ESP#383]
**Bug description**
Raw wifi password is sent over /ws endpoint when config is retieved via endpoint

**Steps to reproduce**
1) Open web interface
2) login
3) look to nettwork comunication

**Expected behavior**
wifi password is not returned in raw form. Basically it should be locked inside device and never returned. 

**Screenshot**
![pass](https://user-images.githubusercontent.com/3290003/81394602-79681000-9122-11ea-8315-c05d221537f8.png)

**Device information**
using ems-esp 1.9.5

**Comment by proddy** [comment]
yes, its awful. In v2 I threw all the web code away and took a different approach during the Christmas break last year. Now it's in React and TypeScript. Each restful endpoint is protected and issues a JWT which is then sent using Bearer Authentication. The code is in a separate project and I'll merge into in master when the core of v2 is complete.

And because of this I'm no longer making any further improvements to 1.9.x
